# Generated by Django 4.2.6 on 2023-10-08 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='Name',
            new_name='ApplicantName',
        ),
    ]
