# Generated by Django 4.2.6 on 2023-10-08 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_applicant_applicantname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experience',
            old_name='applicantId',
            new_name='applicant',
        ),
    ]
